config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy] do #イベント
      resource :bookmarks, only: [:create, :destroy]                                     #ブックマーク
      resources :event_comments, only: [:create, :destroy]                               #コメント
      resources :groups do                                                               #グループ
        get "join" => "groups#join"
        delete "withdrawal" => "groups#withdrawal"
        resources :chats, only: [:create, :destroy]                                      #グループチャット
      end
      collection do                                                                      #検索
        get "search"
      end
    end
    #タグによって絞り込んだ投稿を表示するアクションへのルーティング
    resources :tags do
      get 'events', to: 'events#searchtag'
    end
    resources :users, only: [:show, :edit, :update, :mybookmark] do                      #ユーザー情報
      get :check, on: :collection
      patch :withdrawal, on: :collection
      get :bookmark, on: :collection #ブックマーク
    end
  end

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    resources :event_comments, only: [:index, :destroy]
    resources :events, only: [:index, :show, :destroy]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :event_image
  belongs_to :user

  #タグのリレーション
  has_many :event_tags, dependent: :destroy
  has_many :tags, through: :event_tags, dependent: :destroy

  #ブックマークのリレーション
  has_many :bookmarks, dependent: :destroy

  #コメントのリレーション
  has_many :event_comments, dependent: :destroy

  #グループのリレーション
  has_many :groups, dependent: :destroy

  #バリデーション
  validates :name, presence: true
  validates :introduction, presence: true
  validates :season_start, presence: true
  validates :season_end, presence: true
  validates :time_start, presence: true
  validates :time_end, presence: true
  validates :place, presence: true

  validate :start_end_check

  #開始日と終了日の逆転防止
  def start_end_check
    return false if season_start.blank? || season_end.blank?
    errors.add(:season_end, "は開始日より前の日付は登録できません。") unless
    self.season_start <= self.season_end
  end

  # イベント画像
  def get_event_image
    unless event_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      event_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    event_image
  end

  # 検索機能
  def self.search(search)
    if search != ""
      Event.where(['name LIKE(?) OR place LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Event.includes(:user).order('created_at DESC')
    end
  end

  # タグ機能
  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tagname) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tagname: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tagname: new)
      self.tags << new_post_tag
    end
  end

  # ブックマーク機能
  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @events = Event.page(params[:page]).order(created_at: :desc)
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to admin_events_path
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/index.html.erb
<div class="container my-5">
  <div class="row">
    <h4 class="mb-4 ml-5">イベント一覧</h4>
  </div>
  <div class="row px-5">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th style="width: 40%">ユーザー名</th>
          <th>イベント名</th>
        </tr>
      </thead>
      <tbody>
        <!--イベント一覧表示-->
      <% @events.each do |event| %>
        <tr>
          <td><%= event.user.name %></td>
          <td><%= link_to event.name, admin_event_path(event.id), class: "text-reset border-bottom border-dark" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <!--ページネーション-->
  <div class="row justify-content-center mt-5">
    <%= paginate @events %>
  </div>
</div>

app/views/admin/events/show.html.erb
<div class="container">
  <div class="row justify-content-center my-5">
    <div class="col">
      <div class="modal-body text-center mb-3">
        <!--イベント詳細-->
        <div class="d-flex justify-content-center">
          <h1><%= @event.name %></h1> <!--イベント名-->
        </div>
        <p class="text-muted">
          <% if @event.season_start == @event.season_end %> <!--イベント期間-->
            <%= l @event.season_start %>
          <% else %>
            <%= l @event.season_start %>〜<%= l @event.season_end %>
          <% end %>
        </p>
        <div class="img-container"><%= image_tag @event.get_event_image, size: "300x300", class: "img-fluid d-block mx-auto mb-3" %></div> <!--イベント画像-->
        <p><%= safe_join(@event.introduction.split("\n"),tag(:br)) %></p> <!--イベント詳細-->
        <ul class="list-inline">
          <li>
            <strong>時間: </strong>
            <% if @event.time_start == @event.time_end %>
              <%= l @event.time_start, format: :time %>
            <% else %>
              <%= l @event.time_start, format: :time %>~<%= l @event.time_end, format: :time %>
            <% end %>
          </li>
          <li>
            <strong>場所: </strong>
            <%= @event.place %>
          </li>
          <li>
            <strong>料金: </strong>
            <% if @event.price.present? %>
              <% if @event.price == 0 %>
                無料
              <% else %>
                <%= @event.price.to_s(:delimited) %>円
              <% end %>
            <% else %>
              未設定
            <% end %>
          </li>
        </ul>
        <div class="text-dark text-break"><i class="fas fa-tag"></i> <%= @event.tags.map(&:tagname).join(', ') %></div> <!--タグ-->
        <div class="mt-3">
          <%= link_to "イベントを削除する", admin_event_path(@event), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-danger rounded-pill" %>
        </div>
      </div>
    </div>
  </div>
</div>