config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy] do #イベント
      resource :bookmarks, only: [:create, :destroy]                                     #ブックマーク
      resources :event_comments, only: [:create, :destroy]                               #コメント
      resources :groups do                                                               #グループ
        get "join" => "groups#join"
        delete "withdrawal" => "groups#withdrawal"
        resources :chats, only: [:create, :destroy]                                      #グループチャット
      end
      collection do                                                                      #検索
        get "search"
      end
    end
    #タグによって絞り込んだ投稿を表示するアクションへのルーティング
    resources :tags do
      get 'events', to: 'events#searchtag'
    end
    resources :users, only: [:show, :edit, :update, :mybookmark] do                      #ユーザー情報
      get :check, on: :collection
      patch :withdrawal, on: :collection
      get :bookmark, on: :collection #ブックマーク
    end
  end

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    resources :event_comments, only: [:index, :destroy]
    resources :events, only: [:index, :show, :destroy]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  #イベントのリレーション
  has_many :events, dependent: :destroy

  #ブックマークのリレーション
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_events, through: :bookmarks, source: :event

  #コメントのリレーション
  has_many :event_comments, dependent: :destroy

  #グループのリレーション
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy

  #チャットのリレーション
  has_many :chats ,dependent: :destroy

  #ユーザーアイコン
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/icon_no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image
  end

  #ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # end_user.confirmed_at = Time.now
      user.name = "ゲスト"
    end
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page]).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 col-sm-12 mx-6 mx-sm-auto px-auto my-5">
      <h3 class="mb-5 border-bottom text-center"><span>プロフィール編集</span></h3>
      <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
        <div class="mx-auto">
          <dl class="row">
            <dt class="col-3 mb-3"><%= f.label :profile_image, "プロフィール画像", class: "text-right" %></dt>
            <dd class="col-8 mb-3"><%= f.file_field :profile_image, class: "form-control", accept: "image/*" %></dd>

            <dt class="col-3 mb-3"><%= f.label :name, "名前", class: "text-right" %></dt>
            <dd class="col-8 mb-3"><%= f.text_field :name, class: "form-control name", placeholder: "名前" %></dd>

            <dt class="col-3 mb-3"><%= f.label :email, "メールアドレス", class: "text-right" %></dt>
            <dd class="col-8 mb-3"><%= f.text_field :email, class: "form-control information", placeholder: "sample@mail.com" %></dd>
            
            <dt class="col-3 mb-3"><%= f.label :is_deleted, "ユーザーステータス", class: "text-right" %></dt>
            <dd class="col-8 mb-3">
              <%= f.radio_button :is_deleted, :false %>
              <%= f.label :is_deleted, "有効", value: "false", class: "mr-3" %>
              <%= f.radio_button :is_deleted, :true %>
              <%= f.label :is_deleted, "退会", value: "true" %>
            </dd>

          </dl>
          <div class="form-group row my-5">
            <%= f.submit "変更を保存", class:"btn btn-success col-4 offset-4" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container my-5">
  <div class="row">
    <h4 class="mb-4 ml-5">ユーザー一覧</h4>
  </div>
  <div class="row px-5">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>ユーザーID</th>
          <th>アイコン</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= image_tag user.get_profile_image, size: "50x50" %></td>
          <td><%= link_to user.name,admin_user_path(user.id), class: "text-dark border-bottom border-dark" %></td>
          <td><%= user.email %></td>
          <td>
            <% if user.is_deleted == false %> <!--ユーザーステータス管理-->
              <strong class="text-success">有効</strong>
            <% else %>
              <strong class="test-muted">退会</strong>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="row justify-content-center mt-5">
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-3">
      <div class="img-container"><%= image_tag @user.get_profile_image, size: "100x100", class: "rounded-circle" %></div>
      <h3><%= @user.name %></h3>
      <div><%= @user.email %></div>
      <div>ユーザーステータス</div>
      <% if @user.is_deleted == false %>
        <strong class="text-success">有効</strong>
      <% else %>
        <strong class="text-denger">退会済み</strong>
      <%end%>
      <div><%= link_to "プロフィール編集", edit_admin_user_path %></div>
    </div>
    <div class="col-md-6 mx-auto">
      <% if @events.present? %>
        <% @events.each do |event| %>
          <%= link_to event_path(event.id) do %>
            <div class="card flex-md-row mb-4 shadow h-md-250">
              <div class="img-container"><%= image_tag event.get_event_image, size: "220x220", class: "card-img-left flex-auto d-none d-lg-block" %></div>
              <div class="card-body d-flex flex-column align-items-start">
      
                <h4 class="mb-0 text-dark"><%= event.name.truncate(13) %></h4> <!--イベント名-->
      
                <div class="mb-1 text-muted"> <!--イベント期間-->
                  <span>期間：</span>
                  <% if event.season_start == event.season_end %>
                    <%= l event.season_start %>
                  <% else %>
                    <%= l event.season_start %>~<%= l event.season_end %>
                  <% end %>
                </div>
      
                <div class="mb-1 text-muted"><span>場所：</span><%= event.place.truncate(16) %></div> <!--イベント場所-->
      
                <div class="card-text text-dark mb-auto"><%= event.introduction.truncate(40) %></div> <!--イベント説明-->
      
                <div class="text-dark"><i class="fas fa-tag"></i> <%= event.tags.map(&:tagname).join(', ').truncate(18) %></div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>投稿はまだありません</p>
      <% end %>
      <div class="row justify-content-center mt-5">
        <%= paginate @events %>
      </div>
    </div>
    <div class="col-md-3">
      
    </div>
  </div>
</div>