config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy] do #イベント
      resource :bookmarks, only: [:create, :destroy]                                     #ブックマーク
      resources :event_comments, only: [:create, :destroy]                               #コメント
      resources :groups do                                                               #グループ
        get "join" => "groups#join"
        delete "withdrawal" => "groups#withdrawal"
        resources :chats, only: [:create, :destroy]                                      #グループチャット
      end
      collection do                                                                      #検索
        get "search"
      end
    end
    #タグによって絞り込んだ投稿を表示するアクションへのルーティング
    resources :tags do
      get 'events', to: 'events#searchtag'
    end
    resources :users, only: [:show, :edit, :update, :mybookmark] do                      #ユーザー情報
      get :check, on: :collection
      patch :withdrawal, on: :collection
      get :bookmark, on: :collection #ブックマーク
    end
  end

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    resources :event_comments, only: [:index, :destroy]
    resources :events, only: [:index, :show, :destroy]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, uniqueness: { scope: :event_id }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :message, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :event_image
  belongs_to :user

  #タグのリレーション
  has_many :event_tags, dependent: :destroy
  has_many :tags, through: :event_tags, dependent: :destroy

  #ブックマークのリレーション
  has_many :bookmarks, dependent: :destroy

  #コメントのリレーション
  has_many :event_comments, dependent: :destroy

  #グループのリレーション
  has_many :groups, dependent: :destroy

  #バリデーション
  validates :name, presence: true
  validates :introduction, presence: true
  validates :season_start, presence: true
  validates :season_end, presence: true
  validates :time_start, presence: true
  validates :time_end, presence: true
  validates :place, presence: true

  validate :start_end_check

  #開始日と終了日の逆転防止
  def start_end_check
    return false if season_start.blank? || season_end.blank?
    errors.add(:season_end, "は開始日より前の日付は登録できません。") unless
    self.season_start <= self.season_end
  end

  # イベント画像
  def get_event_image
    unless event_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      event_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    event_image
  end

  # 検索機能
  def self.search(search)
    if search != ""
      Event.where(['name LIKE(?) OR place LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Event.includes(:user).order('created_at DESC')
    end
  end

  # タグ機能
  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tagname) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tagname: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tagname: new)
      self.tags << new_post_tag
    end
  end

  # ブックマーク機能
  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  #バリデーション
  validates :comment, presence: true
end

app/models/event_tag.rb
class EventTag < ApplicationRecord
  belongs_to :event
  belongs_to :tag
  
  validates :event_id, presence: true
  validates :tag_id, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :chats, dependent: :destroy #グループはたくさんのメッセージを持っている

  belongs_to :event
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :event_tags, dependent: :destroy, foreign_key: "tag_id"
  # タグは複数の投稿を持つ　それは、post_tagsを通じて参照できる
  has_many :events, through: :event_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  #イベントのリレーション
  has_many :events, dependent: :destroy

  #ブックマークのリレーション
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_events, through: :bookmarks, source: :event

  #コメントのリレーション
  has_many :event_comments, dependent: :destroy

  #グループのリレーション
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy

  #チャットのリレーション
  has_many :chats ,dependent: :destroy

  #ユーザーアイコン
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/icon_no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image
  end

  #ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # end_user.confirmed_at = Time.now
      user.name = "ゲスト"
    end
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @events = Event.page(params[:page]).order(created_at: :desc)
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to admin_events_path
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page]).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/event_comments_helper.rb
module Admin::EventCommentsHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error_message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-center text-white pt-4 pb-5">
   <div class="container mt-4">
     <div class="mx-auto">
       <p><%= link_to "© 2023 Evencher", new_admin_session_path, class: "text-reset" %></p>
     </div>
   </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark text-white ">
    <div class="container">
      <!--ロゴ-->
      <% if request.path.match(/\/admin(\/)?/) && admin_signed_in?%>
        <a class="navbar-brand" href="/admin"><%= image_tag 'logo.png', size: '280x100' %></a>
      <% elsif user_signed_in? %>
        <a class="navbar-brand" href="/events"><%= image_tag 'logo.png', size: '280x100' %></a>
      <% else %>
        <a class="navbar-brand" href="/"><%= image_tag 'logo.png', size: '280x100' %></a>
      <% end %>
      <!--ハンバーガーメニュー-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!--メニュー-->
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if request.path.match(/\/admin(\/)?/) && admin_signed_in?%>
            <li class="nav-item">
              <%= link_to admin_users_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">ユーザー管理</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_events_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">投稿管理</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_event_comments_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">コメント管理</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, class:"a-header", method: :delete do %>
                <div class="nav-link a-header rounded-pill">ログアウト</div>
              <% end %>
            </li>
          <% elsif request.path.match(/\/admin(\/)?/) %>
            <li class="nav-item">
              <%= link_to new_admin_session_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">ログイン</div>
              <% end %>
            </li>
          <% elsif user_signed_in? %>
            <li class="nav-item">
              <%= link_to new_event_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">イベント投稿</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to events_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">イベント一覧</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">マイページ</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, class:"a-header", method: :delete do %>
                <div class="nav-link a-header rounded-pill">ログアウト</div>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">アカウント作成</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class:"a-header" do %>
                <div class="nav-link a-header rounded-pill">ログイン</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_guest_sign_in_path, class:"a-header", method: :post do %>
                <div class="nav-link a-header rounded-pill">ゲストログイン(閲覧用)</div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<%= form_with(url: search_events_path, local: true, method: :get, class: "search-form") do |f| %>
  <div class="input-group no-border">
    <%= f.text_field :keyword, class: "form-control search-control", placeholder: "Search..." %>
    <%= button_tag type: "submit", class: "btn btn-outline-secondary search-btn " do %>
    <i class="fas fa-search"></i>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evencher</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>